### ISSUE TITLE
Shortcode non fonctionnels

### ISSUE THREAD

**Issue by jbonlinea** [ptibogxiv/doliconnect#1]
Hi,
I just installed doliconnect and doliconnector.

I belive they are connected as in doliconnect > key and settings > dolibarr statut is 
Status: 200
Version: 9.0.1
Access Locked: 0

What is the issue 

I can't save a page with the [doliaccount] shortcode
If I create an accound, I can't log in, and the link toward the "form" is brocken 
`http://mydomain.fr/doliaccount/wp_lostpassword_url(get_permalink`

how to reproduce it ?
create a page "doliconnect main" 
in doliconnect > doliconnect > dolibarr accounrt > select doliconnect main
edit the "doliconnect main", here I can add [dolilogin] shortcode and save the page, but if I add [doliaccount] wordpress refuse to save the page.
The same thing happen if I add the two shortcodes in one shortcode bloc or two

What happends : 

If save a page with [dolilogin] in a shortcode bloc, the block display [dolologin] and the botom of  the page, below the botom wideget area of the 2019 wp theme contains something, it's "loading" and then only display "traitement".

**Comment by jbonlinea** [comment]
I close the issue as it's a draft, I'm fine tuning the issue I'm facing

**Comment by ptibogxiv** [comment]
@jbonlinea i will fix it later with a better shortcode ;) (i do monthly  / weekly update)

**Comment by jbonlinea** [comment]
yes I say the plug-in was updated recently.
Actually I might be interested in the pro version, I'm testing various solution to help an association to switch to dolibarr to manage it's memebership.
But I first would like to knwo what the plugin offres and if it fits our needs


ps, je suis français

**Comment by ptibogxiv** [comment]
pour une asso, il vous faudra aussi adherentsplus d'installer en plus du module adhérent (PR en cours pour l'intégration des fonctions ds le core)

**Comment by jbonlinea** [comment]
Bonjour, 

Je prolonge mes test/feedback

wp fraichement installé, 
doliconnect configuré

- creation d'une page "my dolibarr account"  contenant les shortcode [doliaccount] [dolilogin] 
--> erreur à la sauvegarde
- wp > pages > my dolibarr account > modifier
--> la page est tout de même sauvegardée
--> l'affichage bug
![Capture du 2019-04-09 10-28-42](https://user-images.githubusercontent.com/23659411/55785893-83e54f80-5ab3-11e9-809e-43d84130fee3.png)



- dans doliconnect > dolibarr_account > page "my dolibarr account" ==> sauvegarde
--> ca semble bien sauvegardé

- https://monsitewp.fr/my-dolibarr-account/
--> [doliaccount] semble marcher ? (en partie au moins)
--> [dolilogin] non 
![Capture du 2019-04-09 10-40-08](https://user-images.githubusercontent.com/23659411/55786122-f6562f80-5ab3-11e9-8abf-68ea974d3b07.png)

**Comment by ptibogxiv** [comment]
pour les shortcodes et associé je vous ai répondu par email te je vous expliquerais par entretien de vive voix.

pour l'écran, c'est normal, le comportement de la page est lié au tier qui est cloturé. En effet , les furtures evolutions de dolibarr notamment lié a la rgpd vont tenir compte de ce critère pour en automatiser les suppression à x mois dans le cadre d'une conservation non illimité des données.

**Comment by ptibogxiv** [comment]
no more shortcodes ;)
