### ISSUE TITLE
Adhésions - question et pb divers

### ISSUE THREAD

**Issue by Kwagga-Quagga** [ptibogxiv/doliconnect#10]
Bonjour, 

une issue un peu large, mais nécessaire pour cadrer le problème.

---

# Contexte

Le module Adhérent+ prévoit différent paramètre pour caractériser un adhérent dont : 
 - état (ouvert/clos)
 - soumis à cotisation (oui/non)
 - adhésion automatique (oui/non)
 - renouvellement auto (oui/non)

Ces paramètres vont determiner le comportement de doliconnect vis-àvis des adhérents.

les test sont fait avec stripe configuré sur dolibarr et en mode bac à sable

---

# Constats

### constat A
Pour qu'un type d'adhérent soit proposé par [doliaccount] > adhésion/abonnement, il faut que  état soit ouvert ET que soumis à cotisation  soit oui

A vue de nez, c'est balot ! 
- un seul paramètre, etat, devrait pouvoir suffire à filtrer si oui ou non ce type d'adhésion est disponible.
- on peu souhaiter proposer des adhésions gratuite

Concernant la gratuité : 
Il est bien sûr possible de faire un type d'adhérent dont l'état est ouvert, qui est souis à cotisation, et dont le montant de la cotisation est de 0€.

Cela peut très bien convenir, mais il semble y avoir un bug : 

lorsqu'un utilisateur suit la porcédure pour adhérer, il se rend dans 
[doliaccount] > adhésion / abonnement > devenir membre > souscrire (lorsque l'adhésion est automatique)
ou dans 
[doliaccount] > adhésion / abonnement > devenir membre > nous demander (lorsque l'adhésion n'est pas automatique)

dans un cas comme dans l'autre, l'utilisateur adhére (directement ou après validation) et si "renouvellement auto" est Oui, l'utilisateur est invité à payer sa cotisation.
Or elle est de 0€
1. ce n'est pas très ergonomique, mais admettons
2. l'utilisateur clique sur "payer mon adhésion", 
 - un modal s'ouvre et 
 - l'utilisateur peu alors cliquer sur  "payer" ; 
 - il est rediriger vers [doliaccount] > adhésion abonnement 
     - un message de confirmation apparait "félicitation..."
    - mais son statut est toujours en attente de paiement et, logiquement,  il est toujours invité à payer sa cotisation

![Capture du 2019-04-16 13-12-03](https://user-images.githubusercontent.com/49561217/56205267-90d0e880-6049-11e9-8076-35d1fe4d3f9e.png)

### constat B
si la cotisation n'est pas de 0€, et que l'utilisateur n'a pas définit de moyen de paiement, le procéssus A 2. ci avant ramène à [doliaccount] qui ne retourne toutefois rien de pertinent.

Ici, on s'attends être redirigé vers une page où l'on puisse choisir l'option de paiement, CB/chèque/virement etc.

un paiement par chèque devrait toujours être proposé, même si l'utilisateur n'a pas renseigné de moyen de paiement.

quoi qu'il est soit, là, on est dans le mur

![Capture du 2019-04-16 13-11-20](https://user-images.githubusercontent.com/49561217/56205433-12287b00-604a-11e9-90fa-d6e74e1a748f.png)

--- 
### constat 3

suite du constat 2 

comme nous l'avons vu, même si un utilisateur n'as pas encre renseigné de moyen de paiement, il s'attends à être orienté vers une page de choix de mode de paiement.

Et s'il est indispensable que l'utilisateur ait renseigné sa carte bleu avant de procéder à un paiement CB, alors il faudrait tout de même lui posposer carte blueu, mais en grissé et l'inviter à remplir "gérer mes modes de paiement" pour débloquer ce mode de paiement. 

Toutefois, depuis [dolicart] sur le site demo, il ne semblé pas nécessaire que l'utilisateur ait rempls "gerer ses moyen de paiement" pour que carte bancaire lui soit proposé au moment du checkout.

**Comment by ptibogxiv** [comment]
constat A
pas de cotisation est différent de cotisation à 0. pas de cotisation = membre d'office = salarié ou statutaire et c un champ de base de dolibarr que je ne peux supprimer. pour l'ergo, je suis coincé par le workflow actuel dans dolibarr... pour le moment pas de possibilité de changer ça.

constat B

avez vous parametrer la page dolicart dans l'admin du module??? le module ne peux trouver la page du panier tout seul...


constat C
si ce moyen de paiement (chèque , virement) n'est pas paramétrer dans dolibarr ni dans les factures... il n'est pas proposé... et non cb pré rempli non nécessaire, c'est optionnel et c'est la loi.

**Comment by Kwagga-Quagga** [comment]
> constat A
> pas de cotisation est différent de cotisation à 0. pas de cotisation = membre d'office = salarié ou statutaire et c un champ de base de dolibarr que je ne peux supprimer. pour l'ergo, je suis coincé par le workflow actuel dans dolibarr... pour le moment pas de possibilité de changer ça.
> 

ok, merci pour les précision, domage pour l'ergo ;)

Ceci dit, même si c'est 0€ le comportement ci après ne me parait pas cohérent (cf post 1 pour les détails)
il est rediriger vers [doliaccount] > adhésion abonnement
- un message de confirmation apparait "félicitation..."
- mais son statut est toujours en attente de paiement et, logiquement, il est toujours invité à payer sa cotisation


> constat B
> 
> avez vous parametrer la page dolicart dans l'admin du module??? le module ne peux trouver la page du panier tout seul...
> 

oui oui, 
et
 - le shortcode marche car sur la page ou se trouve [dolicart] j'ai bien un panier vide
 - j'ai bien configurer les paramètre dans doliconnect ; peut être un lien avec #1 où certains champs de doliconnect enregistré les paramètres dans d'autre champs ?


pour info : quand on clique sur payer, on est pas rediriger vers une page inexistante, mais vers cette url  https://monsite.fr/wordpress/dolibarr-account/?module=members



> constat C
> si ce moyen de paiement (chèque , virement) n'est pas paramétrer dans dolibarr ni dans les factures... il n'est pas proposé... et non cb pré rempli non nécessaire, c'est optionnel et c'est la loi.

ok, je comprends que la loi interdise de forcer les gens à enregistrer leur n° de cb; c'est le comportement que j'attendais d'après mes constat sur le site démo, mais je souhaitais confirmation

Dans le module facturation de dolibarr
 - Chèque est activé
 - virement non, je n'ai pas encore ajouté de compte bancaire à dolibarr

**Comment by Kwagga-Quagga** [comment]
je dis peut être une bétise, 
mais avant de clore cett issue ne faudrait il pas s'assurer que le bug observé découle uniquement de #14 ?
