### ISSUE TITLE
Echec ajout moyen de paiement

### ISSUE THREAD

**Issue by Kwagga-Quagga** [ptibogxiv/doliconnect#11]
Bonjour, 

une limitation de dolibarr/stripe/doliconnect, ou un bug ? 

---
# environnement

php7.2
wp 5.1.1 ; doliconnect 3.4.1 ; 
dolibarr 9.0.2 ; doliconnector 9.0.1 ; adhérent+ 9.0.1 ; stripe (core)

stripe est en mode bac à sable

---

# description du problème

l'ajout d'un moyen de paiement de type carte bancaire depuis [doliaccount] ne marche pas. 

---
# comment reproduire le problème

- remplir le formulaire [doliaccount] > gerer les moyens de paiement > ajouter carte 
- saisir ses données (j'ai testé avec une vraie carte bancaire)
- enregistrer
--> le moyen de paiement n'apparait pas dans [doliaccount]
--> coté doliabrr le tiers à un identifiant client stripe
--> coté stripe le client est bien créé, mais aucune carte n'est enregistré

**Comment by ptibogxiv** [comment]
lire la doc de stripe.... test = carte test, live = vraie carte.

interdiction de faire test avec vraie carte... ;)

**Comment by Kwagga-Quagga** [comment]
ok, avec un numéro de carte bidon j'ai ça, numéro de carte en rouget et bouton ajouter carte grisé :(
![Capture du 2019-04-16 13-59-33](https://user-images.githubusercontent.com/49561217/56207811-f88a3200-604f-11e9-8d0b-9b22fa2cf389.png)

**Comment by ptibogxiv** [comment]
cf doc de stripe.... tout est expliqué

**Comment by Kwagga-Quagga** [comment]
si ça peut servir à d'autres ;)
https://stripe.com/docs/testing#cards
