### ISSUE TITLE
[doliaccount ]Formulaire d'inscription : une nouvelle option 

### ISSUE THREAD

**Issue by Kwagga-Quagga** [ptibogxiv/doliconnect#12]
Hey, 

une proposition de nouvelle option pour le formulaire d'inscription de [doliaccount], mais tout d'abord deux  questions : 

1. y a-t-il un risque à créer plusieurs pages contenant le shrtcodde [doliaccount] ? 

2. est il possible de créer une page dans laquelle le shortcode [doliaccount] retourne directement le formulaire d'inscription  ?  j'entends autrement qu'en mettant un lien personalisé dans un menu avec http://monsite.fr/wordpress/page-de-[doliaccount]/?signup 

l'idée serait d'avoir deux pages
- adhésion, dans laquelle il y ai des explications sur l'adhésion et le formulaire directement en dessous 
- espace membre (ou se connecter), avec simplement le formulaire de connexion ;)

alors oui, dit comme ça une fois connecté, les deux pages/liens nous conduisent exactement à la même chose, mais rien n'empèche de faire un petit script qui controle ce qui apparait dans le menu en fonction de notre statut de connexion ;)

---
autrement 

la version actuelle,  dite "normale" présente quelques champs
la version kiosque en présente bcp plus

pour devenir adhérent, il faut avoir remplis tout les champs proposé en mode kiosque.
Si l'utilisateur à créer son compte via le formulaire version normale, et s'engage dans le processus d'adhésion il est redirigé vers ses information personnelles, puis peut remplir sa demande d'adhésion.

Très bien ça marche

mais pourquoi ne pas proposer une option permettant de choisir entre forulaire simple et formulaire complet, mais qui ne soit pas du mode kiosque (dont l'objet est de ne pas vérifier l'adresse email  / confirmer l'inscription ).

comme ça, quand on sais déjà que nos utilisateurs seront tous adhérents, on les faits remplir un formulaire une fois, directement disponible sur la page adhésion, et on en parle plus ;)

**Comment by ptibogxiv** [comment]
pour le moment pas fait  mais à réfléchir pour une option...

non il n'y aura 2 pages mais il y a la possibilité de créer une page quelconque sur le wordpress et d'y inclure le block gutenberg "membership" qui va proposer les types , les prix et l'adhésion. A priori, je ne pense pas supporter d'autres workflow.

je tiens à garder un coeur/ noyau de module valide pour tous comme dans Dolibarr. La gestion des adhésion et satellite et optionnel comme d'autres addons

**Comment by Kwagga-Quagga** [comment]
ok,

c'est quoi le block gutenmber "membership", un truc dynamique ou c'est un simple block à remplr manuellement ?

peut être ajouter le label ehencement aussi  ?

**Comment by ptibogxiv** [comment]
c'est un bloc que le module rajoute dans le nouvel editeur de wordpress gutenberg... un bloc dynamique qui s'autogère et récupére les données

**Comment by Kwagga-Quagga** [comment]
ok, mais il est pas encore inclus dans la v 3.4.1 ?

**Comment by ptibogxiv** [comment]
si il est inclus depuis les premières versions bloc "membership" dans la rubrique widget

**Comment by Kwagga-Quagga** [comment]
ah ? bon ben soit je suis benet soit on a encore un pb quelque part

![Capture du 2019-04-16 18-29-28](https://user-images.githubusercontent.com/49561217/56227386-a2c88080-6075-11e9-8866-1cf9f61c96b8.png)
