### ISSUE TITLE
[dolishop] lien cassé + panier ne se remplis pas + bug similaires

### ISSUE THREAD

**Issue by Kwagga-Quagga** [ptibogxiv/doliconnect#13]
Bonjour, 

un bug ? 

---
# environnement

php7.2
wp 5.1.1 ; doliconnect 3.4.1 ; 
dolibarr 9.0.2 ; doliconnector 9.0.1 ; adhérent+ 9.0.1

---
# description du problème

[dolishop] ne redirige pas correctement l'utilisateur

---
# comment reproduire le problème

## cas 1 wp-user non connecté

- aller sur [dolishop], 
- choisir une catégorie de produit, puis sur un article (produit ou service dolibarr)
- sous le tarif, il y a un bouton connexion 
- cliquer dessus, 
-->on est directement redirigé vers cette même page et non la page de connexion 

voici le lien que le bouton contient : 
https://monsite.fr/wordpress/dolibarr-account/&redirect_to=https://monsite.fr/wordpress/dolibarr-shop/?category=1

lien vers lequel on est réellement conduit : 
https://monsite.fr/wordpress/dolibarr-shop/?category=1

## cas 2 wp-user connecté

- aller sur [dolishop], 
- choisir une catégorie de produit, puis sur un article (produit ou service dolibarr)
- sous le tarif, un menu déroulant permet de choisir la quantité d'article souhaité et un bouton nous invite à l'ajouter ua panier
- choisir autre chose que 0 pour la quantitié
- cliquer sur ajouter
--> l'article n'est pas ajouté au panier
--> on est redirigé vers cette même page mais à moitiée crashée, le bandeau noir wp en haut n'apparait pas ! 

url/action derrière le bouton : voir screenshot

lien vers lequel on est réellement conduit : 
url https://monsite.fr/wordpress/dolibarr-shop/?category=1&product=1

![Capture du 2019-04-16 17-13-09](https://user-images.githubusercontent.com/49561217/56221817-3e082880-606b-11e9-811b-655316ea91cf.png)

**Comment by ptibogxiv** [comment]
bug répéré... juste activer le module de commande dans dolibarr.... si pas de commande = pas de panier ^^

**Comment by Kwagga-Quagga** [comment]
je réouvre, pour communiquer plus simplement ; 

# précision sur la situation / environnement

module comande activé dans dolibarr, 
pas de problème pour ajouter un service ou un produit à une comande depuis l'interface dolibarr ; et pas de pb pour valider la comande

# liens cassé hier marche aujourd'hui

### hier, 
pour un utilisaeur non connecté à wp
 dans [dolishop] > bouton "connectez-vous" > on n'était pas redirigé vers [doliaccount], mais revenais directement dans [dolishop]


### aujourd'hui 
pour un utilisaeur non connecté à wp
 dans [dolishop] > bouton "connectez-vous" > on n'correctement redirigé vers [doliaccount].

# micro conclusion

le panier ne se remplis toujours pas, et : 
- ce n'est probablement pas parce qu'il est impossible d'ajouter les produits ou services testé dans [dolishop] à une comande dans dolibarr
- ce n'est probablement pas à cause d'un problème côté serveur en lien avec les redirection et la fonction wp_redirect_(url)
