### ISSUE TITLE
doliconect settings : bug à la sauvegarde

### ISSUE THREAD

**Issue by Kwagga-Quagga** [ptibogxiv/doliconnect#14]
Bonjour, 

un bug ? 

---
# environnement

php7.2
wp 5.1.1 ; doliconnect 3.4.1 ; 
dolibarr 9.0.2 ; doliconnector 9.0.1 ; adhérent+ 9.0.1

---
# description du problème

problème de sauvegarde des settings dans doliconnect. 
les  menu déroulant pour indiquer les pages ou se trouvent les [shortcode] ne s'enregistre pas correctement

---
# comment reproduire le problème

créer les page wp, y inclure les shortcode et sauvegarder (pour les bug voir ici #1 )
- dolibarr_account : [doliaccount]
- dolibarr_cart : [dolicart]
- dolibarr_shop :  [dolishop]
- dolibarr_contact : [dolicontact]
- dolibarr_donation : [dolidonation]

aller dans doliconnect > paramètres

informé les menu déroulant avec les page corespondante

--> la saisie du menu déroulant pour dolicontact n'est pas sauvegardé
--> la saisie du menu déroulant pour dolidonation est sauegardé dans le champs de dolicontact. 

![Capture du 2019-04-16 17-35-04](https://user-images.githubusercontent.com/49561217/56223923-fc797c80-606e-11e9-9bdd-455901bba61b.png)

![Capture du 2019-04-16 17-43-58](https://user-images.githubusercontent.com/49561217/56224075-44989f00-606f-11e9-9947-9e1fd235a88a.png)

---
### problèmes liés ? 

il semble que doliconnect ait des dificulté à trouver faire le lien entre les pages
[dolishop] et [doliaccouns] : voir ici #13 
[dolishop] et [dolicart] : voir ici #13 
[doliaccount] et [dolicart] : voir ici #10

**Comment by ptibogxiv** [comment]
bug vu.... merci wordpress c'est suite  à la dernière version ....

**Comment by Kwagga-Quagga** [comment]
ok, j'ai ajouté deux sceenshot
