### ISSUE TITLE
Echec paiement Stripe mode bac à sable

### ISSUE THREAD

**Issue by Kwagga-Quagga** [ptibogxiv/doliconnect#15]
tentative de paiement d'un service par cb via stripe en mode bac à sable
tout va bien, mais après avoir cliqué sur paiement on est redirigé vers ça  
![Capture du 2019-04-17 18-25-39](https://user-images.githubusercontent.com/49561217/56304941-76793680-613f-11e9-9e4f-848c60b4ab61.png)

**Comment by ptibogxiv** [comment]
faut que je regarde d'ou ça vient...

**Comment by Kwagga-Quagga** [comment]
observation du jour

maintenant on est redirigé vers le panier, qui apparait vide ; la commande est bien créé, mais n'apparait pas comme payé dans dolibarr

**Comment by ptibogxiv** [comment]
fixé !
