### ISSUE TITLE
Block gutemberg ne sont pas proposés

### ISSUE THREAD

**Issue by Kwagga-Quagga** [ptibogxiv/doliconnect#17]
php 7.2
wordpress 5.1.1
doliconnect 3.4.2 (++)

les block gutemberg de doliconnect ne sont pas proposés sauf si un module tel que gutemberg advance block est installé et activé

la question des block qui ne sont pas proposé à été evoqué ici #12

**Comment by ptibogxiv** [comment]
non retrouvé sur une nouvelle installation en wordpress 5.2.1
