### ISSUE TITLE
Adhésion - Commande : Workflow différentiel si produit ou service ? (ehencement?)

### ISSUE THREAD

**Issue by Kwagga-Quagga** [ptibogxiv/doliconnect#19]
Bonjour

Il s'agit d'avantage d'une question, mais à de l'importance au niveau du workflow. 

Dolibarr est configuré de la sorte : 
- les module adhérent(+), comande, service,  produit, et facturation sont actifs
- dans dloibarr/configuration > module > adhérents+ > un **service** est définit pour être utilisé pour la ligne de cotisation dans la facture
- type d'ahdérent  AAAA
    - adhésion de groupe : non
    - soumis à cotisation : oui
    - adhésion automatique : oui
    - renouvellement auto : oui

Prenons le cas d'un nouvel utilisateur-wp tiers-dolibar.
Celui-ci souhaite adhérer à l'association.

il va donc dans [doliaccount] > adhésion abonnement > devenir membre
il suis la procédure et choisi le paiement par chèque
--> dans dolibarr il y a donc 

- une comande "validée", mais non traitée
- une adhésion "validée", mais non payé
    --->tout va bien

l'asociation reçoit le chèque et 

- confirme la cotisation à l'adhésion
    --> mais la comande reste à l'état validé, or elle devrait/pourait être traitée. Celà éviterait de devoir faire deux manipulations, d'une part valider l'adhésion et d'autre part la comande.

**Ici je suis bien dans le cas ou la cotisation est associé à un service**

bien sûr dans le **cas ou la cotisation pour l'adhésion est associé non pas à un service, mais à un produit,** le workflow ci dessus est très bien, car si l'adhésion est associé à l'envoie par courrier d'une carte d'adhérent par exemple,  il permet de séparer la réception du paiement de l'adhésion (adhésion validé et payé) et l'envoi de la carte (comande traitée)

**Comment by ptibogxiv** [comment]
qd on reçoit le cheque.... il faut en saisir la facture depuis la commande qui automatiquement mettre à jour l'adhésion. Dolibarr ne peut faire le lien qd on fait le sens inverse...

il faut en gros traiter la commande come n'importe laquelle et si il y a une adhésion dedans avec le produit/servicé dédié avec des date sde début / fin,  ça se fera tout seul. Dans l'autre sens  depuis le module adhérents plus  ou adhérent, le lien ne peux être refait vers la commande.

**Comment by Kwagga-Quagga** [comment]
ok, good to know ! 

une fois de plus le workflow dolibarr n'est pas orienté vers la gestion des adhésions, 

merci bcp

**Comment by ptibogxiv** [comment]
en efet le centre ets le tiers, le reste sont des adddons qui gravite autour.... et qui donne des "propriétés" au tiers central.
