### ISSUE TITLE
Synchro WP <=> Doli ne marche pas pour les champs "nom" et "prénom"

### ISSUE THREAD

**Issue by Kwagga-Quagga** [ptibogxiv/doliconnect#2]
Bonjour, 

une limitation de dolibarr, de wp, ou un bug ? 

---
# environnement

php7.2
wp 5.1.1 ; doliconnect 3.4.1 ; 
dolibarr 9.0.2 ; doliconnector 9.0.1 ; adhérent+ 9.0.1

---
# description du problème

les modifications effectuées sur les champs "prénom" et "non" ne sont pas synchronisées/répercutées

---
# comment reproduire le problème
## cas wp --> doli
créer ou éditer un compte utilisateur-wp depuis [doliaccount] 
les changements sont répercutés sur le tiers-dolibarr liée, sauf pour les champs "nom" et "prénom"
les changements de nom et prénom sont toutefois sauvegardé pour l'utilisateur-wp

## cas doli --> wp
éditer un compte utilisateur depuis dolibarr > utilisateurs et groupes > fiche utilisateur
les changements sont répercutés sur l'utilisateur-wp liée, sauf pour les champs "nom" et "prénom"
les changements de nom et prénom sont toutefois sauvegardé pour le tiers-dolibarr

---
# notes
cas le plus fréquent d'un utilisateur qui créé son compte depuis [doliaccount]. Il fait une coquille, ou souhaite ajouter un second prénom (jean --> jean-marc), il sera en mesure de le modifier pour wp, mais pas dolibarr

**Comment by ptibogxiv** [comment]
c'est le comportement de base de dolibarr.. la gestion pro / perso pour les tiers n'est pas optimal... à réfléchir comment améliorer cela pour que ça soit accepter sur le core

**Comment by Kwagga-Quagga** [comment]
Bonjour, 

Je me trompe peut être mais j'ai l'impression que votre réponse concerne d'avantage l'issue #5 

Quoi qu'il est soit jai reformulé mon premier post pour clarifier le problème identifié. 

 ---

je ne suis pas certain que dans le cadre de doliconnect/or il soit nécessaire de modifier dolibarr en profondeur.


dans le sens [doliaccount] --> dolibarr, n'est il pas possoble d'écraser le contenu du champs "nom du tiers" de dolibarr avec le contenu des champ "nom" et "prénom" avec le même script qui à servi à la création du compte ?

Dans le sens inverse, modification d'un nom de tiers dans dolibarr vers wp

ne serait-iil pas possible d'ajouter un regex qui reconnaisse sépare le champs "nom du tiers" de dolibar en deux à partir du permier espace ? 

pa exemple le champ nom du tier de dolibarr contient initialement "aaaa bbbb", 
je le modifie dans dolibarr pour "xxxxx yyyy" et le regex reconnait et sépare "aaaa bbbb" ou "wxxxxx yyyy "xxxx", " ", "yyyy"


(cf mon premier post)

**Comment by Kwagga-Quagga** [comment]
fermé par erreur, pardon

**Comment by ptibogxiv** [comment]
euh...  oui mais... Dolibarr n'est pas si simple... et il y a des noms pros composés...  le problème est lié dans la gestion de dolibarr de la notion de tiers pro ou particulier

**Comment by Kwagga-Quagga** [comment]
> euh... oui mais... Dolibarr n'est pas si simple... et il y a des noms pros composés... le problème est lié dans la gestion de dolibarr de la notion de tiers pro ou particulier

oui c'est vrai, je tentais une pirouette. 


Mais ceci soulève une question : 
dolibarr distingue-t-il les tiers pro des tiers particulliers ? 
Il y a bien le champs type de tiers qui le suggère, mais ce champs a il des répercutions ?
J'entends par là, ce champs n'est pas obligatoire, mais le fait de choisir une option va elle avoir des conséquence (ex imposer de remplir certains autres champs tel que le numéro sirene) ou ne sert qu'à des fins analytique de stratégie marketing ? 

Si comme je le suppose, un tiers est un tiers, et les champs de la fiche tiers "type de tiers" ou "type d'entité légale" on un caractère purement informatif/analytique, alors pourquoi faire deux version du formulaire d'inscription dans [doliaccount] ?



mais grrr, j'avais éditer mon premier post avec plein d'info, mais aparement je l'avais pas sauvegardé 


en résumé ça traitait de la correspondance des champs

| [doliacocunt] | utilisateur-wp | tiers dolibarr |
| --- | --- | --- |
| adresse electronique | adresse de messagerie | email |
| non d'affichage | pseudonyme | x |
| nom | nom | nom du tiers |
| prénom | prénom | nom du tiers |
| nom de la société | x | ? voir #6   |

**Comment by ptibogxiv** [comment]
@Kwagga-Quagga parceque dans les adhérents et autres on a besoin de ce renseignement... le principe c'est la propagation des infos et la récupération à la volée des informations requises.

Actuellement la gestion est en effet informatique dans dolibarr et pas optimisé. J'attend de voir comment de prochaines Pull Request concernant la gestion de la tva tiers pro/perso et selon pays va optimiser pour bouger de ce point de vue

**Comment by jbonlinea** [comment]
Bonjour 

je reprends cette issue, qui semble partiellement réglée depuis le passage à dolibar 10.X et les version de doliconnect qui vont avec.

wp 5.2.3
dolibarr 10.0.2
doliconnect 3.10.3
doliconnect pro 3.10.1
doliconnector 10.0.2
adhérent + 10.0.2

je viens de changer les noms et prénom d'un utlisateur depuis doliconnect, le changement et bien répoercuté dans  les utilisateur wp et dans le tiers  dolibarr.

Je n'ai pas fais les tests en sens inverse, en modifiant depuis l'interface de wordpress, ni depuis le tier ddolibarr directement

**Comment by ptibogxiv** [comment]
Je pense que c'était un ensemble de facteur entre les 2 qui posait pb. Il reste tjs à résoudre le sens dolibarr vers WordPress en écriture et modification

**Comment by ptibogxiv** [comment]
je ferme cet issue car en soit la synchro fonctionne, c'est surtout un pb dolibarr où cette gestion particulier / pro n'est pas optimum y compris dans la derniere version v11. Modif a fa ire d'abord dans dolibarr avant que je puisse l'integrer au mieux
