### ISSUE TITLE
Commande adhésion 0€ ne va pas dans le panier

### ISSUE THREAD

**Issue by Kwagga-Quagga** [ptibogxiv/doliconnect#20]
follow up de l'issues  #13 

nouvel utilisateur
[doliaccont] > adhésion > devenir membre > choixir type d'adhérent

on est redirigé vers 

[doliacount] > adhésion > cliquer sur le bouton payer mon adhésion 
- si le type d'utilisateur à une cotisation > 0€
   ---> pas de soucis on est redirigé vers le panier
- si le type d'utilisateur à une cotisation = 0€
    ---> on n'est pas redirigé et l'adhésion reste à payer

il n'y a donc pas de comandes qui sont générer dans dolibarr.... 
par contre l'adhésion est bien confirmé, mais demeure à payer...

**Comment by ptibogxiv** [comment]
fixed
