### ISSUE TITLE
[doliacount] confidentialité : envoi des infos ne marche pas

### ISSUE THREAD

**Issue by Kwagga-Quagga** [ptibogxiv/doliconnect#21]
Bonjour, 

 ---

PHP 7.2
wp 5.1.1
dolibarr 9.0.2, doliconnect 3.4.2

---
pb
bug à l'envoi des données personnelles 

---
comment le reproduire

 [doliaccount] > confidentialité > exporter vos donnes > valider la demande

--> page blanche avec écrit 0 tout en haut à gauche et ce lien dans la barre d'adresse du navigateur : https://test.quagga.fr/wordpress/wp-admin/admin-ajax.php

le mail avec les données n'est pas envoyé/reçu

**Comment by ptibogxiv** [comment]
bug vérifié... correctif en cours....

**Comment by ptibogxiv** [comment]
fixé dans la prochaine version majeure ;)

**Comment by Kwagga-Quagga** [comment]
:+1:
