### ISSUE TITLE
[doliaccount] paramètre de sécurité : impossible de changer les réglages

### ISSUE THREAD

**Issue by Kwagga-Quagga** [ptibogxiv/doliconnect#22]
Bonjour 

php 7.2
wp 5.1.1
dolibarr 9.0.2, doliconnect 3.4.2

dans [doliaccount] > paramètre de sécurité, impossible de changer les réglages pour les trois switch, ni de changer de langue

**Comment by ptibogxiv** [comment]
en cours d'investigation lié a wordpress 5.1

**Comment by ptibogxiv** [comment]
fixed !
