### ISSUE TITLE
warning on update

### ISSUE THREAD

**Issue by Kwagga-Quagga** [ptibogxiv/doliconnect#23]
Bonjour, 
un message d'erreur lors de la mise à jour vers 3.5.4

`Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'update' not found or invalid function name in /home/.../www/wp-includes/class-wp-hook.php on line 286`

**Comment by ptibogxiv** [comment]
bug pas retrouvé sur 3 mises à jour... enquête à suivre

**Comment by Kwagga-Quagga** [comment]
hum, oui pardon, c'est lors de la mise à jour vers doliconnect pro 1.7.4 

désolé

**Comment by ptibogxiv** [comment]
pas retrouvé sur la mise à jour 1.7.5. a priori fixé

**Comment by Kwagga-Quagga** [comment]
retrouvé sur deux install avec la 1.7.5 :(

l'une marche (celle sur laquelle j'ai fais plein de test et des feedback ici même) l'autre souffre de #24

**Comment by ptibogxiv** [comment]
pas sur que ça soit moi cet erreur.... à suivre pour que je puisse la reproduire.

**Comment by ptibogxiv** [comment]
résolu non retrouvé sur les dernieres versions
