### ISSUE TITLE
Fatal error sur [doliaccount]

### ISSUE THREAD

**Issue by Kwagga-Quagga** [ptibogxiv/doliconnect#24]
j'ai ça qui apparait sur [doliaccount]

Recoverable fatal error: Object of class WP_User could not be converted to string in /home/.../www/wp-content/plugins/doliconnect/doliconnect.php on line 298

**Comment by ptibogxiv** [comment]
sur quel page ? dans quel contexte etc....

**Comment by Kwagga-Quagga** [comment]
oui pardon ce n'est pas très détaillé ;)

on va se retrouver avec plusieurs bug en même temps je crois ;)

- une page qui ne contient que [doliaccount]

--- 

### historique 

j'ai configure dolibarr et wp comme habituellement

avec le premier compte admin de wp, qui n'a pas de tiers dolibarr, j'avais bien "compte utilisateur bloqué"

--- 

sur un autre navigateur, 
- page [doliaccount],  
- saisi du formulaire,
- mail de confirmation avec lien pour choix de mdf
--> je ne suis pas invité à choisir mon mdp, mais à me connecter ou créer un comtpe

l'utilisateur wp existe, pas le tiers dolibarr
je supprime l'utilisateur wp et recommence

---

après avoir fait ça 2-3 fois j'ai cette erreur sur [doliaccount] en étant déjà connecté en tant que premier admin de wp.

**Comment by ptibogxiv** [comment]
lié au serveur je pense... utilisé en live actuellement et aucun pb.... version de php ou autre qui fait planter ou si l'utilisateur de base utilisé n'a pas les infos essentielles de rempli : nom prenom email login

**Comment by Kwagga-Quagga** [comment]
pour test / info 

downgrade sauvage : ça remarche... sur les deux...
 

suppression de doliconnect pro et normal via interface wp.

réinstall de doliconnect 3.4.3 (que j'avais en local) 

plus d'erreur

**Comment by ptibogxiv** [comment]
Faut que je trouve pourquoi... Erreur fluctuante et lié à php

**Comment by Kwagga-Quagga** [comment]
php 7.2 sur les deux install ;)

**Comment by Kwagga-Quagga** [comment]
doliconnect 3.4.7
doliconnect pro 1.7.5 

`
Fatal error: Uncaught ArgumentCountError: Too few arguments to function dolimembership_modal(), 1 passed in /var/www/.../wp-content/plugins/doliconnect-3.4.7/functions/dashboard.php on line 1308 and exactly 3 expected in /var/www/.../wp-content/plugins/doliconnect-pro/doliconnect-pro.php:968 Stack trace: #0 /var/www/.../wp-content/plugins/doliconnect-3.4.7/functions/dashboard.php(1308): dolimembership_modal(NULL) #1 /var/www/.../wp-includes/class-wp-hook.php(286): members_module('https://test.qu...') #2 /var/www/.../wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #3 /var/www/.../wp-includes/plugin.php(465): WP_Hook->do_action(Array) #4 /var/www/.../wp-content/plugins/doliconnect-3.4.7/doliconnect.php(437): do_action('options_dolicon...', 'https://test.qu...') #5 /var/www/..../wp-content/plugins/doliconnect-pro/doliconnect-pro.php on line 968`

**Comment by Kwagga-Quagga** [comment]
doliconnect 3.5.4.2
doliconnect pro 1.6.1

`Recoverable fatal error: Object of class WP_User could not be converted to string in /home/www/.../wp-content/plugins/doliconnect/doliconnect.php on line 298`

**Comment by ptibogxiv** [comment]
il faut impérativement  les 2 dernieres version de chaque sinon bug en raison de changement important dans les fonctions

**Comment by Kwagga-Quagga** [comment]
ok, mais les deux dernières crash franco, 
alors qu'avant ça marchait...

as tu un tableau avec les versions de doliconnect et pro qui marchent ensemble ?

**Comment by ptibogxiv** [comment]
non pas de tableau, il faut juste utiliser les 2 dernières pas de retrocomptabilité avec les anciennes

**Comment by Kwagga-Quagga** [comment]
je demande que ça, mais c'est compliqué quand les deux dernières ne marchent pas alors qu'avant oui

**Comment by ptibogxiv** [comment]
la seule erreur qui peut poser pb est celle du  premier post les autres sont liés aux mauvaises versions

le problème est bien à la création de compte ?

**Comment by Kwagga-Quagga** [comment]
problème #23 à la mise à jour

impossible de créer compte, 

puis erreur ci dessus pour le compte wp admin

**Comment by ptibogxiv** [comment]
fixé
