### ISSUE TITLE
impossible de créer un compte

### ISSUE THREAD

**Issue by Kwagga-Quagga** [ptibogxiv/doliconnect#25]
Bonjour, 

---
# environnement

fresh install 

mutualisé infomaniak avec php7.2
wp 5.1.1 ; doliconnect 3.5.4.2 ; doliconnet pro 1.7.5 
dolibarr 9.0.1 ; doliconnector 9.0.1 ; adhérent+ 9.0.2

---
# description du problème

il est impossible de créer un nouveau compte

---
# comment reproduire le problème

- aller sur [doliaccount]
- suivre la procédure pour ajouter un compte (dolibarr_register est bien coché pour tous le monde)
- suivre le lien reçu par mail 
- on n'est pas redirigé vers  la page de saisi de mote de passe, mais la page de connexion

l'utilistateur wp est bien créé mais on ne peut pas se connecter
pas le tiers dolibarr

---
# note

install de doliconnect 3.5.4.2 depuis le dépot de plug-in wordpress
install de doliconenct pro en 1.6.1 puis upgrade n 1.7.5 (pas le chois j'ai pas d'autre version en local

**Comment by ptibogxiv** [comment]
focntionnel pour moi... je viens de faire 50 tests au moins. la page mon compte est t'elle renseigné dans les parametres du module ?

**Comment by ptibogxiv** [comment]
tester avec la version master et non la publié 3.5.4.2

**Comment by Kwagga-Quagga** [comment]
> tester avec la version master et non la publié 3.5.4.2

ok je reviens à toi

**Comment by ptibogxiv** [comment]
fixé
