### ISSUE TITLE
Bug information personelle

### ISSUE THREAD

**Issue by Kwagga-Quagga** [ptibogxiv/doliconnect#26]
Bonjour

un compte peut être de type : 
- compte personnel
- compte professionnel

quand on créé un compte, puis suis la procédure pour effectuer un achat, il nous faut saisir les infrmations personnelles complémentaires.

jusqu'ici tout va bien

mais si l'on retourne à la boutique, et reprend l'achat en cours, il nous est de nouveau demandé de renseigné nos informations personnelles.
Ce que nous avons saisi précédement et bien sauvegardé, mais par défaut, le bouton radio est sur "compte professionnel" ajoutant le champs obligatoire "société".
or quand on est une personne physique, on à absolument rien à remplir ici, et il n'est pas possible de basculer vers compte personnel...

bref on est bloqué (bien sur il y a des pirouette, comme renseigner une société, puis basculer sur compte perso, mais c'est pas joli)

**Comment by ptibogxiv** [comment]
ça c'est prév aujourd'hui ou demain pour préparer le choix de contact de livraison ^^ corriger rapido cette semaine

**Comment by Kwagga-Quagga** [comment]
:+1: 

merci

**Comment by ptibogxiv** [comment]
fixé mais pas encore poussé mais c'est fixé
