### ISSUE TITLE
Renouvellement adhésion : comportement innatendu (voir bug)

### ISSUE THREAD

**Issue by jbonlinea** [ptibogxiv/doliconnect#28]
Bonjour 

je viens de faire un essai de renouvellement d'adhésion et suis face à un comportement innatendu

#### environnement 
wp 5.2.3
dolibarr 10.0.2
doliconnect 3.10.3
doliconnect pro 3.10.1
doliconnector 10.0.2
adhérent + 10.0.2

tout les paramètre de l'adhésion sont réglé afin de permettre l'adhésion et le renouvellement d'adhésion auto

#### comportement de la première adhésion

lors d'une première adhésion, l'utilisateur va sur doliaccount > adhésion > adhérer --(
- (la première fois) il est redirigé vers la page information personnelles

- puis il est redirigé sur doliconnect > adhésion : il choisi le type d'adhésion

- il est redirigé vers la page doliaccount > adhésion avec maintenant écrit "payer mon adhésion", 

- il engage la procédure de paiement, passe par dolicart, puis dolicheckout

- il est redirigé vers sa commande qu'il peut suivre.

 #### comportement attendu pour le renouvellement de l'adhésion

le comportement attendu pour le renouvellement de l'adhésion est le même que pour la première adhésion, les étapes préalables relatives aux informations personnelles en moins

#### comportement observé pour le renouvellement d'adhésion

doliaccount > adhésion > renouveller mon adhésion > modal annuler/renouveller >  choisir renouveller 

- ici l'utilisateur est redirigé vers dolicart, puis dolicheckout (et non vers doliccount > adhésion)

- suivant le fil, l'utilisateur effectue le checkout -->

- il est maintenant redirigé vers dolicaccount > adhésion

- et il lui ai demandé de payer l'adhésion (ce que l'on vient de faire)

==> déja c'est pas très logique, mais continuons

-  l'utilisteur clique sur payer adhésion > dolicart > dolicheckout --> le renouvellement d'adhésion est prit en compte.

**Comment by Kwagga-Quagga** [comment]
Je relance ce fil pour avoir des nouvelles du procéssus de renouvellement des adhésions.

je viens de refaire un essai, dans doliaccount > adhésions > renouveller mon adhésion > modal > renouveller (en face du type d'adhésion correspopndant) > on est dirigé vers dolicart ... on suis le procéssus

j'ai choisi un paiement par chèque. 

la commande est créé dans dolibarr  ; 

si on classe la commande livrée et  facturédans dolibarr, je retrouve bien ça dans doliaccount > "suivi des commandes". Par contre coté dolibarr le classement de la commande facturée et livrée ne créé pas la cotisation coté adhérent et dans doliaccount > adhésion celle-ci est toujours en attende de paiement
 
comment se fait il que la cotisation n'a pas été crée automatiquement lors de la facturation et livraison de la commande ?  c'est le cas lors d'une première adhésion
 (j'ai classé la commande facturé et livré, mais sans avoir créer de facture car je ne veux pas pourir mon facturier et je vais supprimer l'adhésion et la commande - ceci dit ça marche pour les première adhésions donc pourquoi pas en renouvellement)


Est ce que calà fait la même chose avec un paiement par carte ? 
ce serait encore pire, même catastrophique


ps, si je recommence le procéssus de renouvellement d'adhésions, une deuxième commande est créé.... ps : ca rejoint un peu cett issue #10 



il me semble que pour éviter de perdre l'utilisateur et que ce soit la pagaille dans dolibarr, qu'il faut gérer ça légèrement différement (je sais qu'il y a des contrainte coté dolibarr)
Si un adhérent commence le procéssus dre renouvellement d'adhésion, et que celui ci n'est pas finalisé car on est en attente de paiement, doliaccount > adhésion ne dois plus proposer de renouveller l'adhésion (c'est fait), mais de la payer, comme c'est le cas dans la commande
