### ISSUE TITLE
Champs non sauvegardé lors de création de compte en mode kiosque [doliaccount]

### ISSUE THREAD

**Issue by Kwagga-Quagga** [ptibogxiv/doliconnect#3]
Bonjour, 

une limitation fonction inachevée ou un bug ?  

---
# environnement

php7.2
wp 5.1.1 ; doliconnect 3.4.1 ; 
dolibarr 9.0.2 ; doliconnector 9.0.1 ; adhérent+ 9.0.1

---
# description du problème

dans [doliaccount], en mode Kiosque, les champs Téléphones, Adresse, Ville, Code postal, et Pays ne sont pas sauvegardées lors de la création de l'utilisateur.

Ils sont toutefois  sauvegardés si l'on édite les informations personnelles de l'utilisateur par la suite.

---
# comment reproduire le problème

Activer le mode kiosque pour votre ip depuis les préférence de doliconnect

Se déconnecter

Créer un compte depuis [doliaccount] et sauvegarder

Consulter les informations personnelles : les champs Téléphone, Addresses, Ville, Code postal et Pays sont vides bien qu'ils aient été saisis précédement

---
# notes

**Comment by ptibogxiv** [comment]
Je clos cet issue, ça sera corrigé en 3.4.3

**Comment by Kwagga-Quagga** [comment]
super !
