### ISSUE TITLE
update or overide translation 

### ISSUE THREAD

**Issue by Kwagga-Quagga** [ptibogxiv/doliconnect#33]
**Describe the bug**

More of a question : 
 - what is the best way to override a translation file ?
Shall I add a pair of  .mo/.po doliconnect translation file into /wp-content/language/plugin/ ?

 - what am I suppose to do so the string I edit in the po file are applied in front-end ? (beyon empty transcient and clear cache on server, clear cache and history on broswer)

**Comment by ptibogxiv** [comment]
pas possible de faire override à part modifier manuellement le fichier (mais écraser en mise a jour) ou utiliser un module tiers wordpress qui le permet. Les traduction sont lier au module pour le moment et non encore diffusé par wordpress donc dans /wp-content//plugin/doliconnect/languages

si c'est un pb... faire une PR

**Comment by Kwagga-Quagga** [comment]
yes merci, 

pas de soucis pour la 1, 

pour la 2e question j'ai modifier le fichier .po, mais ça ne s'applique pas en front

par exemple
ligne 1590 : remplacer "compte personel" par "ccompte personel (personne physique)
ligne 1594 : remplacer "compte entreprise" par "compte entreprise ou association (personne morale)

mais ça ne change rien dans doliaccount > information personnelles ?! 
j'ai vidé le cache du serveur et navigateur, les transcient, l'historique de navigation... rien à faire ? 

Même testé avec le plugin loco translate, mais pas mieux ! 

la c'est pas un pb doliconnect, mais je ne comprends pas trop non plus
