### ISSUE TITLE
.list-group-item.active : Z index

### ISSUE THREAD

**Issue by Kwagga-Quagga** [ptibogxiv/doliconnect#34]
**Describe the bug**

the css class .list-group-item.active z-index is set to "2" which permit it to be above other content it is not uppose to hide

**Comment by ptibogxiv** [comment]
librairie bootstrap, voir avec pour correctif (la v5 est une grosse refonte sans jquery et full css)

**Comment by Kwagga-Quagga** [comment]
yep, il passe au dessus d'autre éléments avec un z-index 10, ça fait partie des pb doliconnect-divi

réglé en ajoutant un custom css

z-index: 1 !important;


ps : bootstrap 5 n'est pas pure css, mais CSS et JS, et abandon de jquery (ce qui ne réjouis pas tout le monde apparement)

**Comment by ptibogxiv** [comment]
Peut être mais c'est les pb de compatibilité jquery (grosse incompatibilité entre versions) qui sera resolu
