### ISSUE TITLE
Mail d'adhésion ou cotisation n'ont pas la pièce jointe

### ISSUE THREAD

**Issue by Kwagga-Quagga** [ptibogxiv/doliconnect#37]
### dans dolibarr > configuration > module > adhérent/+ > email
Modèle d'email électronique à utiliser pour envoyer un courrier électronique à un membre lors de l'enregistrement d'une nouvelle cotisation

est définit sur un modèle de mail

### dans dolibarr > configuration > email > modèle > mdoèle choisi ci dessus >
la valeur de l'option "joindre le fichier" est "1", mais la pièce jointe n'est pas ajouté au mail

### comportement attendu
on s'attends à ce que la facture soit en pièce jointe

**Comment by ptibogxiv** [comment]
ne sera pas résolu dans doliconnect, nécessite des ajouts Dolibarr  en cours de soumission (facture dans facture, modele de commande dans commande etc) comme les emails adhérents issus des templates

exemple:
https://github.com/Dolibarr/dolibarr/pull/13564
