### ISSUE TITLE
Carnet d'adresse : comportement peu ergonomique

### ISSUE THREAD

**Issue by Kwagga-Quagga** [ptibogxiv/doliconnect#4]
Bonjour, 

---
# environnement

php7.2
wp 5.1.1 ; doliconnect 3.4.1 ; 
dolibarr 9.0.2 ; doliconnector 9.0.1 ; adhérent+ 9.0.1

---
# description du problème

Dans wp [doliaccount], le comportement de l'édition des fiches de contacts dans "gérer le carnet d'adresse" est un peu surprenant. 

Lorsque l'on a créé le un compte depuis wp [doliaccount]  :

- Lors de la première saisie de la fiche, le champs "titre/poste" n’apparaît pas, mais 
 - lorsqu'on édite une fiche déjà existante, le champ "titre/poste" est obligatoire

On à du mal à comprendre ce que l'on nous veut ? 
 - titre ? tout le monde n'est docteur, maître ou autre 
- poste ? lequel, dans l'asso, dans la vie... et si on est retraité, ou chômeur 

d'accord quand à l'utilité de ce champs, mais 
- c'est préférable de le faire apparaître dès la première édition (on ne revient que rarement sur sa fiche)
- pourquoi le rendre obligatoire

**Comment by ptibogxiv** [comment]
Modifié!

**Comment by Kwagga-Quagga** [comment]
:+1: 

:)
