### ISSUE TITLE
Mode de paiement enregistrés [ergonomie] [dolicart- checkout]

### ISSUE THREAD

**Issue by Kwagga-Quagga** [ptibogxiv/doliconnect#44]
Je me demande quel est l'intéret d'avoir un bouton radio "pas mode de paiement enregistré" lorsque justement on n'en as pas ? 

Si l'utilisateur n'as pas choisi de mode de paiement favori, ou de carte, pourquoi ne pas simplement ne pas avoir de valeur par défaut pour les bouton radio, ou alors la CB.

Dans tous les cas, il me semble préférable de ne pas avoir ce "pas de mode de paiement enregistré" dans la mesure ou il ne sert à rien et impose à l'utilisateur d'en changer

cf screenshot
![Capture du 2020-04-07 17-25-01](https://user-images.githubusercontent.com/49561217/78688113-32a1b300-78f5-11ea-9676-49f83b8e6797.png)

**Comment by ptibogxiv** [comment]
pcq sinon le JS derriere plante lol donc faudra attendre que ça soit passé en ajax pour que cela soit changé ^^

**Comment by Kwagga-Quagga** [comment]
ok !

**Comment by Kwagga-Quagga** [comment]
je laisse ouvert, afin que l'idée persiste pour la version ajax du système de paiement
