### ISSUE TITLE
--Feature Request-- Tutorial for connecting woocommerce

### ISSUE THREAD

**Issue by bf8392** [ptibogxiv/doliconnect#45]
Hi :-) I like your solution and want to integrate it with a woocommerce shop, but I'm not totally sure how to do that...I would work out a tutorial with your help if you like :-) you can use it for your docs :-) would be really nice to see if we can work that out :-)

**Comment by ptibogxiv** [comment]
we should create an addon and use woocommerce hook for call dolibarr with my callDoliApi() function
(by default i developped my own eshop within doliconnect for better integration with dolibarr and all settings)

**Comment by bf8392** [comment]
Ahhh okay I see...hmm didn't test your shop yet...I'll look into it :-)

**Comment by ptibogxiv** [comment]
> Ahhh okay I see...hmm didn't test your shop yet...I'll look into it :-)

it's basic  but efficient (work in progress for more ajax, templating and dolibarr's options support)

**Comment by bf8392** [comment]
Would it be possible do build a connector for woocommerce and contact form 7 into your plug-in? Because with this you get the best out of both worlds and won't have to develop all by yourself :-)

**Comment by ptibogxiv** [comment]
> Would it be possible do build a connector for woocommerce and contact form 7 into your plug-in? Because with this you get the best out of both worlds and won't have to develop all by yourself :-)

Actually i don't have time for this dev but i can valid good pull request with this add ;)

**Comment by bf8392** [comment]
Maybe I can help a little :-). This plug-in offers the functionality I mean for contact form 7, but is not developed anymore...maybe you can integrate it, and I can help with testing :-). https://github.com/ATM-Consulting/module_wordpress_contact-form-7-to-dolibarr
It has some missing functionality like fields for e-mail Marketing, and it doesn't recognize duplicates...but everything else is working :-)

**Comment by bf8392** [comment]
Oh and here is a plug-in for woocommerce (also not developed/supported) but you can use code :-) https://github.com/OPEN-DSI/ecommerceng_woosync

**Comment by bf8392** [comment]
Your plug-in is much more advanced as you can see connection and you're still developing and supporting...your plug-in would be the only one with this sync-functionality :-) maybe you can sell it in dolistore :-). The problem I see in programming store, forms and so on everything by yourself, you will need a lot of time and never get the functionality of woocommerce and contact form 7. I LOVE your plug-in because you're the only Opensource developer I know, who develops for WordPress and dolibarr connection, which is desperately needed for dolibarr... because the main issue with dolibarr is it's integration into other programs...but it's okay if you don't integrate it :-) keep up your cool work for dolibarr band WordPress it's much appreciated :-) I'm closing this for now, as you can open up a pull-request if you want to integrate :-) have a nice day :-)
