### ISSUE TITLE
my_login_logo_url already declared

### ISSUE THREAD

**Issue by aureleduda** [ptibogxiv/doliconnect#48]
**Describe the bug**
Testing on a already set wordpress installation, I can't activate the extension because I have already a my_login_logo_url() in my functions.php

**To Reproduce**
Create a function my_login_logo_url()  in the theme functions.php. The extension can't be activated.

It should be better to use a less common name for common filters, something like  ptibogxiv_login_logo_url() for instance

**Comment by ptibogxiv** [comment]
Thnak you! it's fixed in next release
