### ISSUE TITLE
Affichage du menu adhesion sur la partie compte ne s'affiche pas

### ISSUE THREAD

**Issue by ocarette** [ptibogxiv/doliconnect#49]
Lorsque la personne s'identifie, la partie [account] n'affiche pas la partie adhesion.

Wordpress 5.7
Doliconnect 5.3.1
Dolibarr 13.0.2
Doliconnector 13.0.2
Adherentplus 13.0.2

Un type d'adhérent a été créé qui n'est pas à 0€, validation auto et renouvellement auto.

Malgré plusieurs essai de création de personne via le site Wordpress ou en creant un adherent dans Dolibarr, création d'un tiers via cet adherent et lié au site Wordpress, aucun menu d'adhésion sur la page Compte n'apparait.

Y a t il une configuration particulière à mettre en place ?

Merci d'avance pour la réponse
Olivier

**Comment by ptibogxiv** [comment]
Bonjour,

 avez vous bien activer le module adhérent et adhérents plus ?
il faut aussi purger les transient de wordpress si vous faites des changements de paramètrages ( les paramètres de dolibarr sont stockés piur 1 mois de base)
