### ISSUE TITLE
Problème d'affichage des liens et des listes

### ISSUE THREAD

**Issue by ocarette** [ptibogxiv/doliconnect#50]
Ton plugin est super bien.
J'ai téléchargé un thème wordpress et lorsque j'installe doliconnect, les liens se souligne et les liste apparaissent systèmatiquement avec des puces alors que normalement cela n'apparait.
Sais tu si il y a moyen de limiter ce problème ?

**Comment by ptibogxiv** [comment]
il faut corriger les css du theme et d'autres modules chargés pour les rendre compatibles avec celui du module pour simplifier mon developpement (bootstrap 5) il faut mettre des !important aux bons endroits.
