### ISSUE TITLE
Improve description and list features

### ISSUE THREAD

**Issue by dpriskorn** [ptibogxiv/doliconnect#55]
I don't understand what this plugin DOES. What is the purpose of it? Does it make it easy to make a webshop in wordpress with the Dolibarr-API/database as a backend?

What features does it have? What is missing?

**Comment by ptibogxiv** [comment]
this FREE plugin create a frontend customer space with reports from Dolibarr

there is a simple shop too

i support 80% of dolibarr features and settings (not new features of v14 yet)
