### ISSUE TITLE
[doliaccount] Echec création compte pro

### ISSUE THREAD

**Issue by Kwagga-Quagga** [ptibogxiv/doliconnect#6]
Bonjour, 

un bug ? 

---
# environnement

php7.2
wp 5.1.1 ; doliconnect 3.4.1 ; 
dolibarr 9.0.2 ; doliconnector 9.0.1 ; adhérent+ 9.0.1

---
# description du problème

la sasie du formulaire d'inscription [doliacount] pour un compte pro crée un utilisateur-wp, mais pas le tiers-dolibarr correspondant

---
# comment reproduire le problème
 
testé uniquement en mode kiosque

aller sur wordpress [doliaccount] > créer un compte > compte pro

remplir le formulaire d'inscription et valider

**Comment by ptibogxiv** [comment]
la création du tiers dans dolibarr ne se fait qu'a la connexion ce qui evite de polluer dolibarr de tiers ne se connectant pas au moins une fois.

**Comment by Kwagga-Quagga** [comment]
> la création du tiers dans dolibarr ne se fait qu'a la connexion ce qui evite de polluer dolibarr de tiers ne se connectant pas au moins une fois.

en mode kiosque, on est directement connecté à wp. 
même si je me déconnecte et reconnecte de wp [doliaccount] le tier dolibarr n'est pas créé.

dans dolibarr ? les id/pass saisi ne marche pas, et ça semble normal [doliaccont] est cencé créer un tiers-dolibarr par un utilisateur-dolibarr

**Comment by ptibogxiv** [comment]
Je vais regarder... 

WordPress ne synchronisera que les utilisateur dolibarr lier à des tiers et ayant un email.

**Comment by Kwagga-Quagga** [comment]
> Je vais regarder...
> 
> WordPress ne synchronisera que les utilisateur dolibarr lier à des tiers et ayant un email.

oui, mai en l'occurence, je crois que là n'est pas la question.


en mode kiosque, je crée un comtpe pro depuis [doliaccount], 
 - le compte utilisateur-wp est crée, 
 - je suis loggé dans wp, 
 - mais le tier-dolibar n'est pas créé.
 - si je me déconnecte et reconnecte sur wp avec ce compte nouvellement créer, le tier-dolibarr n'est toujours pas créé

Si je fais la même chose, toujours en mode kiosque, avec un compre personnel créer depuis [doliaccount], 
- le compte utilisateur-wp est créé, et 
- le tiers-dolibarr aussi. 

ça c'est factuel, et reproductible 

après il y a plus d'une subtilité du workflow de doliconnect/or qui m'échappe donc le pb vient peut être aussi de là ;)

**Comment by ptibogxiv** [comment]
@Kwagga-Quagga j'ai trouvé ça sera corrigé en 3.4.3

**Comment by Kwagga-Quagga** [comment]
:+1: 
super 
merci
