### ISSUE TITLE
Module SHOP - Produits / services non visible

### ISSUE THREAD

**Issue by egalliari** [ptibogxiv/doliconnect#63]
Bonjour, 
Je n'arrive pas a retrouver les produits/services qui sont dans mon Dolibarr sur Wp
Le module commande est activé côté Dolibarr. Les autres infos remontent bien. 

![image](https://user-images.githubusercontent.com/48688561/157694549-96bd1ed9-594d-44e7-b22c-897c829d6e32.png)

Environnement technique : 
Dolibarr 15
WP 9.5.1
Doliconnector 15 

Merci pour votre aide !

**Comment by egalliari** [comment]
Si je met en url 
monsite.fr/shop/?product=1
Le produit est visible :
![image](https://user-images.githubusercontent.com/48688561/157695027-2a198cd8-9d28-4a24-83b0-4cf6c8a8b600.png)

**Comment by ptibogxiv** [comment]
Bonsoir,

Il faut definir des catégories de produits pour que ceux ci s'affichent.
