### ISSUE TITLE
DoliShop

### ISSUE THREAD

**Issue by jimmygruau** [ptibogxiv/doliconnect#67]
Bonjour, 
Nous avons un problème, nous avons activer l'option DoliCart sur une page mais lorsque nous souhaitons afficher cette page, nous avons "string(50)"Oops, le module de commande n'est pas disponible".
Auriez-vous une solutions ?
Version de Dolibarr : beta-16.0.0
Version de DoliConnect : 6.4.0
Version de DoliConnector : 15.0.1

**Comment by ptibogxiv** [comment]
Bonjour,

vous devez avoir le module commande d'actif sur dolibarr pour que cela fonctionne.

Une fois activé, purger les transients dans wordpress dans lesquels les infos et paramètres de dolibarr sont recopiés.
