### ISSUE TITLE
Suppression compte [doliaccount]

### ISSUE THREAD

**Issue by Kwagga-Quagga** [ptibogxiv/doliconnect#8]
Hello, 
J'ai vu que la fonctionalité pour supprimer un compte est sur la roadmap (cf screenshot).
En attendant quel est le wordflow souhaitable pour supprimer un compte, évidement à la fois au sens utilisateur-wp et tiers-dolibarr ? 

Merci

**Comment by ptibogxiv** [comment]
il faut supprimer dans dolibarr et wordpress manuellement (j'attendais que les fonctions soient stabilisés nativement)

**Comment by Kwagga-Quagga** [comment]
> il faut supprimer dans dolibarr et wordpress manuellement (j'attendais que les fonctions soient stabilisés nativement)

oui, mais ps d'ordre préférentiel ? (histoire que la sychro ne recréé pas l'autre chez l'un en faisant la manoeuvre)

**Comment by ptibogxiv** [comment]
Plutôt d'abord WordPress pour être sur mais si le membre 'est pas connecté pas d' importance

**Comment by Kwagga-Quagga** [comment]
:+1: 
merci

**Comment by Kwagga-Quagga** [comment]
Hum... dificulté

cas d'un utilisateur-wp lié à un tier dolibarr

je supprime l'utilisateur-wp, mais je ne peux pas supprimer le tier-dolibarr

j'ai ce message d'erreur : 
![Capture du 2019-04-18 11-16-24](https://user-images.githubusercontent.com/49561217/56350848-fcdb5a00-61cb-11e9-8ad2-ed6afd195acf.png)



Autrement
le champs utilisateur wp lié est toujours remplis dans la fiche tiers, mais il n'affiche que :   **()**


je pense que ca n'a rien à voir avec le message d'erreur, mais j'essaye de supprimer le lien entre wp-doli, mais ça ne marche toujours pas.

**Comment by ptibogxiv** [comment]
bug de dolibarr ça ne vient pas de moi.... déjà identifié mais pas corrigé encore ni ds v9 ou v10

**Comment by Kwagga-Quagga** [comment]
ok, merci :)

**Comment by ptibogxiv** [comment]
oui ! il me semble que ça a été fixé (par moi lol) en v10 mais que le fix n'a ps été descendu en version inférieur

**Comment by ptibogxiv** [comment]
fixé et publié ds la v10 (doute sur retro portage dans dolibarr v9)
