### ISSUE TITLE
Categories of goods and services are not displayed.

### ISSUE THREAD

**Issue by MatthewWeb** [ptibogxiv/doliconnect#83]
Categories of goods and services are not displayed. Started with version 8.1.0 and higher. Doliconnector updated to 19.02
Dolibarr v 19.02
Apache
Mariadb

**Comment by ptibogxiv** [comment]
Please refresh all your transient and update with the last version. have you some php errors ?

**Comment by ptibogxiv** [comment]
I understand your mistake. you need to activate the widget menu with the catégorie list. a new display is under developement. the category list is no more displayed on the home page of the shop ( maybe later with an optiion but i try to change to a better and speed code.

**Comment by MatthewWeb** [comment]
Thanks, I figured it out! That's even better!
