### ISSUE TITLE
Product Note

### ISSUE THREAD

**Issue by MatthewWeb** [ptibogxiv/doliconnect#84]
Hello! Is it possible to add "Product Note" instead of "Product Description"? "Product Notes" has an editor for formatting text with the addition of images.
![изображение](https://github.com/user-attachments/assets/f9348bbf-1eb5-4927-a47d-e94445cdb418)
![изображение](https://github.com/user-attachments/assets/bdf453a6-ecb7-47b6-a277-2407ee587c43)

**Comment by MatthewWeb** [comment]
I changed "description" to "note_public" in the file /function/product.php and everything worked. Will you add this functionality in the next versions?

**Comment by ptibogxiv** [comment]
yoiu can have an editor for the description too this is an option on Dolibarr
![image](https://github.com/user-attachments/assets/6d4606ee-68d6-4025-bc16-f61eecee56e3)
![image](https://github.com/user-attachments/assets/7c37169d-2c84-41a7-879b-68870e517cac)

**Comment by MatthewWeb** [comment]
In this case, you cannot add images. When manually adding an image with a code, it is deleted when saving
![изображение](https://github.com/user-attachments/assets/22b4917f-3d4c-4a5a-82b6-4348fb562e54)

**Comment by ptibogxiv** [comment]
i invite you to declare this bug  on dolibarr's github.
